### ISSUE TITLE
unittests for connectors

### ISSUE THREAD

**Issue by gryphius** [fumail/fuglu#133]
currently the connectors don't have any unittests which makes it scary to change anything, especially if we want to implement python3 support we need to be sure that changes don't break python2.
( see https://github.com/gryphius/fuglu/pull/128 )

we should also add samples of messages with potential encoding issues (non-ascii charactrers) to the endtoend test.

**Comment by neonknight** [comment]
https://gitlab.com/fumail/fuglu/issues/133
