### ISSUE TITLE
attachment plugin config changes ignored?

### ISSUE THREAD

**Issue by danBLA** [fumail/fuglu#182]
There seems to be an issue here:
https://github.com/fumail/fuglu/blob/de961dcf574e4e0b84dec531b5e60fa2a05a25b0/fuglu/src/fuglu/plugins/attachment.py#L499-L504
It is possible to remove file extensions at runtime. However, since "supported_archive_extensions" is modified directly, there is not way to bring an extension back once it has been removed.

**Comment by neonknight** [comment]
https://gitlab.com/fumail/fuglu/issues/182
