### ISSUE TITLE
Add <to>+spam in msg header

### ISSUE THREAD

**Issue by ananyaaj5** [fumail/fuglu#211]
Hi,

I would like to add "+spam" to the <to> address on envelope and rfc header, if spamassassin adds spam status as yes for a particular mail. How do i do this?

**Comment by ananyaaj5** [comment]
I would also like to know what changes I have to make in archive plugin conf to save the emails/ quarantine them in a particular path if they have high spam score.

**Comment by gryphius** [comment]
fuglu has moved to gitlab a few years ago.. you might want to ask your question over there instead: https://gitlab.com/fumail/fuglu/-/issues
