### ISSUE TITLE
unrar gone from EPEL - find alternative way to handle rar files

### ISSUE THREAD

**Issue by gryphius** [fumail/fuglu#87]
rar / unrar apparently have been removed from EPEL in favour of "unar".
the command line args from unar are unfortunately not the same as in unrar, and the ones from unar are not supported in the rarfile library used in fuglu.

**Comment by neonknight** [comment]
python-rarfile supports bsdtar (from libarchive/libarchive ) as backend. bsdtar is available from RHEL/CentOS standard repositories.

However, bsdtar may not be able to open rar files created using proprietary/non-free extensions of rar.

**Comment by neonknight** [comment]
Closing for now, considering the following:

 * Python support for unar is not available at the moment, wrapping calls of the unar binary with subprocess would be needed for now (no great performance).
 * other distributions such as Debian or Ubuntu still ship unrar as part of their non-free repositories
 * unrar can easily be installed manually or using third party rpms
 * with bsdtar RHEL/CentOS contains a possibility to unpack rar archives

This still leaves ample possibilities for every admin to get rar extraction running without too much hassle. However, all solutions not including the latest non-free unrar will potentially only provide restricted compatibility.
